services:
  mysql:
    image: mysql:8.0
    container_name: studentmanagement-mysql
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    volumes:
      - mysql_data_container:/var/lib/mysql
      - ./StudentManagement.sql:/docker-entrypoint-initdb.d/StudentManagement.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data_container: